<?php

namespace Projects\InsightAPiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnalysisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalysisRepository extends EntityRepository
{
    // Note Analyses refer to Our Own Analyses system (DB)
    // check if the analyse exist in DB, if not render 0
    public function isAnalysis($number)
    {        
        $analy = $this->createQueryBuilder('a')
        ->select('a.id')
        ->where('a.number = :nbr')
        ->setParameter('nbr', $number)
        ->getQuery();
        if(!$analy->getResult()){            
            
            return 0;
        }else
            
        {            
            return $analy;
        }
      
    }
    // get Analysis of the Analyses selected $slug = parent entity ID
    public function childAnalysis($slug)
    {
        
         $analysis = $this->createQueryBuilder('a')
                          ->select('a')
                          ->where('a.analyses = :nbr')
                          ->setParameter('nbr', $slug)
                          ->getQuery();
            
        if(!$analysis->getResult()){            
         
            return 0;
        }else
            
        {            
            return $analysis;
        }
    }
    
    
}
