<?php

namespace Projects\InsightAPiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ViolationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViolationRepository extends EntityRepository
{

	public function byAnalysis($slug)
	{  

		 $viols = $this->createQueryBuilder('v')
				        ->select('v')
				        ->leftJoin('v.violations', 'vs')
				        ->leftJoin('vs.analysis', 'a')
				        ->where('a.number = :nbr')
				        ->setParameter('nbr', $slug)
				        ->getQuery();
				       
				if(!$viols->getResult()){            
				            
				            return 0;
				        }else
				            
				        {            
				            return $viols;
				        }


	}
    

    
    
}
