<?php

namespace Projects\InsightAPiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ViolationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViolationsRepository extends EntityRepository
{
}
